### ISSUE TITLE
请教 CMDB服务怎么停止和启动

### ISSUE THREAD

**Issue by Hylijia** [easycmdb/easycmdb#11]
请问，在操作系统中，有没有什么命令可以停止CMDB的所有服务，和有什么命令可以启动CMDB所有服务。

**Comment by Alren-huang** [comment]
目前没有统一的停止和启动。

服务的部署路径统一为：/usr/local/easyops/xxx
服务的统一停止命令为：easyops stop /usr/local/easyops/xxx
服务的统一启动命令为：easyops start /usr/local/easyops/xxx

可以编写一个shell脚本来做批量
