### ISSUE TITLE
license过期了，安装的时候提示“校验license失败”

### ISSUE THREAD

**Issue by iTraceur** [easycmdb/easycmdb#21]
![image](https://user-images.githubusercontent.com/9270831/127161403-e496f744-164a-4ee0-8f44-ad3a60665804.png)

请问能否更新一下license吗，谢谢！

**Comment by dragonku7** [comment]
@easycmdb 安装出现同样的问题，麻烦更新下license

**Comment by kalsolio** [comment]
@easycmdb 过期了

**Comment by kalsolio** [comment]
license.lic
Expires = 01-May-2021
CMDBExpires = 01-May-2021
DeviceNum = 500
Registered-To = user_0
DeployExpires = 01-May-2021
Product-Name = easyops
Hardware-Locked = No
Product-Edition = Enterprise
Easyops-Code = 
Host-ID = Not-Locked
MonitorExpires = 01-May-2021
ITOAExpires = 01-May-2021
Custom-Object-Limit = 30

**Comment by anlihust** [comment]
这个版本不再支持新安装了，已安装的license会持续更新
11月份会推出新的新版的产品，到时欢迎大家试用

**Comment by dragonku7** [comment]
@anlihust 11月啦，新产品快推出了吗

**Comment by kalsolio** [comment]
> 这个版本不再支持新安装了，已安装的license会持续更新 11月份会推出新的新版的产品，到时欢迎大家试用

新版哪里下载

**Comment by kalsolio** [comment]
@anlihust 新版哪里下载呀
