### ISSUE TITLE
添加本机IP和端口后报错

### ISSUE THREAD

**Issue by xidianwlc** [easycmdb/easycmdb#3]
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

**Comment by easycmdb** [comment]
能否提供更详细的报错信息?  怀疑是客户端ssh受限,该报错说明是SSH认证失败.

**Comment by xidianwlc** [comment]
服务器是centos7.2 内核版本：4.4.38-1.el7.elrepo.x86_64
ssh配置中PasswordAuthentication yes
放开了ssh的一些配置后报错信息发生变更：{"isTrusted":true}
nginx日志显示500报错
172.16.131.227 - - [12/Apr/2019:10:03:23 +0800] "POST /ucpro_service/api/creator/s90320 HTTP/1.1" "-" "-" 500 183 "http://192.168.6.95:4200/installer" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-" "2.552" "2.552" "."
172.16.131.227 - - [12/Apr/2019:10:06:37 +0800] "POST /ucpro_service/api/creator/s90320 HTTP/1.1" "-" "-" 500 183 "http://192.168.6.95:4200/installer" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-" "1.616" "1.616" "."
172.16.131.227 - - [12/Apr/2019:10:10:56 +0800] "POST /ucpro_service/api/creator/s90320 HTTP/1.1" "-" "-" 500 183 "http://192.168.6.95:4200/installer" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-" "2.178" "2.178" "."

**Comment by xidianwlc** [comment]
建议官方提供docker镜像和docker-compose进行发布，方便环境搭建和测试

**Comment by easycmdb** [comment]
您可以按以下操作：
1. 重启ucpro  2. 刷新页面
另外，非常感谢您关于docker方面的建议，我们后续会有相关的支持
