### ISSUE TITLE
离线包安装

### ISSUE THREAD

**Issue by 510908220** [easycmdb/easycmdb#6]
![image](https://user-images.githubusercontent.com/3920302/56950466-21d6b200-6b68-11e9-8eb9-b2b2d4b102d5.png)
使用的是离线包。但是还是一直卡在这个界面

**Comment by easycmdb** [comment]
请参照离线安装指南
https://github.com/easycmdb/easycmdb/blob/master/doc/EasyCMDB%E5%9F%BA%E7%A1%80%E7%89%88%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85%E6%96%B9%E5%BC%8F.md
建议您重新安装试一下

**Comment by blockchainguard** [comment]
环境检查失败，错误详情:Process exited with status 1

**Comment by yanxiao71** [comment]
环境检查失败，错误详情:Process exited with status 1

死活装不上

**Comment by yanxiao71** [comment]
一直卡在这个页面，太不靠谱啦，不如用脚本装

**Comment by yanxiao71** [comment]
![QQ图片20190509104736](https://user-images.githubusercontent.com/43506525/57423841-2fff8f00-7248-11e9-9fe8-daea77070606.png)

一直卡在安装页面，也不知道在那转什么。太不靠谱啦，不如用脚本安装。

**Comment by easycmdb** [comment]
/usr/local/ucpro/log/ucpro_service.log  请查看这份日志，是否有报错信息，如有，请帮忙贴出具体报错信息。

**Comment by yanxiao71** [comment]
2019-05-09T10:27:40.331+0800	ERROR	creator/creator_service.go:495	generate runnerID fail, [100011]ERR_INTERNAL: 环境检查失败，错误详情:Process exited with status 1
2019-05-09T10:27:56.930+0800	ERROR	worker/ssh_worker.go:208	installIp:(10.33.32.151)
, cmd:(/data/easyops/tmp/uc/scripts/uc-worker.py -c init --org 5389059 --hosts 10.33.32.151:mgtdyxqas21v.geniusafc.com)
, stdout:([2019-05-09 10:27:56,914 <module> L250 INFO] receive command, ['/data/easyops/tmp/uc/scripts/uc-worker.py', '-c', 'init', '--org', '5389059', '--hosts', '10.33.32.151:mgtdyxqas21v.geniusafc.com']
[2019-05-09 10:27:56,915 exec_cmd L70 DEBUG] grep "# easyops begin line marked by easyuc" /etc/hosts
[2019-05-09 10:27:56,919 <module> L303 ERROR] error, e=[Errno 2] No such file or directory, traceback=Traceback (most recent call last):
  File "/data/easyops/tmp/uc/scripts/uc-worker.py", line 301, in <module>
    err = op2func[args.command](args)
  File "/data/easyops/tmp/uc/scripts/init_env.py", line 28, in init
    write_hostname(ip2host)
  File "/data/easyops/tmp/uc/scripts/common.py", line 262, in write_hostname
    code, _ = exec_cmd([cmd], check_call=False)
  File "/data/easyops/tmp/uc/scripts/common.py", line 74, in exec_cmd
    proc = sp.Popen(args=cmd, stdout=sp.PIPE, stderr=sp.PIPE, shell=shell, env=env)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory


)
, error:(Process exited with status 1)


2019-05-09T10:27:56.930+0800	ERROR	creator/creator_service.go:495	generate runnerID fail, [100011]ERR_INTERNAL: 环境检查失败，错误详情:Process exited with status 1





------------------ 原始邮件 ------------------
发件人: "EasyCMDB"<notifications@github.com>;
发送时间: 2019年5月9日(星期四) 下午2:19
收件人: "easycmdb/easycmdb"<easycmdb@noreply.github.com>;
抄送: "12零~"<305103010@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [easycmdb/easycmdb] 离线包安装 (#6)




/usr/local/ucpro/log/ucpro_service.log  请查看这份日志，是否有报错信息，如有，请帮忙贴出具体报错信息。

**Comment by blockchainguard** [comment]
搞定了。chmod  -R 改一下目录 权限！

**Comment by yanxiao71** [comment]
意思是安装之前修改/data目录权限吗？还是说我卡在这个步骤之后，将/data目录递归修改权限？




------------------ 原始邮件 ------------------
发件人: "南国利剑"<notifications@github.com>;
发送时间: 2019年5月9日(星期四) 下午3:13
收件人: "easycmdb/easycmdb"<easycmdb@noreply.github.com>;
抄送: "12零~"<305103010@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [easycmdb/easycmdb] 离线包安装 (#6)




搞定了。chmod  -R 改一下目录 权限！

**Comment by easycmdb** [comment]
定位了这块的代码，在python2.7未发现该问题，看起来可能是sp模块的问题，可以

import subprocess as sp
proc = sp.Popen(args=["ls"], stdout=sp.PIPE, stderr=sp.PIPE, shell=True)

将上面代码保存为 sp.py

然后执行
strace -s1000 -f -o /tmp/xx python ./sp.py
这个命令  把/tmp/xx 贴出来看看

**Comment by yanxiao71** [comment]
OK, 那我换python2.7装了看看




------------------ 原始邮件 ------------------
发件人: "EasyCMDB"<notifications@github.com>;
发送时间: 2019年5月9日(星期四) 下午4:34
收件人: "easycmdb/easycmdb"<easycmdb@noreply.github.com>;
抄送: "12零~"<305103010@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [easycmdb/easycmdb] 离线包安装 (#6)




定位了这块的代码，在python2.7未发现该问题，看起来可能是sp模块的问题，可以
 
import subprocess as sp
 proc = sp.Popen(args=["ls"], stdout=sp.PIPE, stderr=sp.PIPE, shell=True)
 
将上面代码保存为 sp.py
 
然后执行
 strace -s1000 -f -o /tmp/xx python ./sp.py
 这个命令  把/tmp/xx 贴出来看看

**Comment by yanxiao71** [comment]
> ![QQ图片20190509104736](https://user-images.githubusercontent.com/43506525/57423841-2fff8f00-7248-11e9-9fe8-daea77070606.png)
> 
> 一直卡在安装页面，也不知道在那转什么。太不靠谱啦，不如用脚本安装。

环境必须依赖pytho2.7 ，换成python2.7，时间同步正常后部署成功
